# Generated by Django 5.1.7 on 2025-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='delivery_time',
            field=models.IntegerField(),
        ),
    ]
