# Generated by Django 5.1.7 on 2025-04-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userresponse_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userresponse'),
        ),
    ]
