# Generated by Django 5.1.7 on 2025-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userresponse_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='package_deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='package_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='package_type',
            field=models.CharField(blank=True, choices=[('BASIC', 'Базовый'), ('STANDARD', 'Стандартный'), ('PREMIUM', 'Премиум')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
