# Generated by Django 5.1.7 on 2025-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userresponse_package_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='selected_bonus_options',
            field=models.ManyToManyField(blank=True, to='main.bonusoption'),
        ),
    ]
