# Generated by Django 5.1.7 on 2025-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.imagestorage'),
        ),
    ]
