# Generated by Django 5.1.7 on 2025-05-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_chat_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='main.orders'),
        ),
    ]
