# Generated by Django 5.1.7 on 2025-05-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_chat_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='main.orders'),
        ),
    ]
