# Generated by Django 5.1.7 on 2025-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_revisionrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercancellation',
            name='other_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercancellation',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отказано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercancellation',
            name='reason',
            field=models.CharField(choices=[('style', 'Не устраивает стиль'), ('tz', 'Не соблюдено ТЗ'), ('other', 'Другое')], max_length=255),
        ),
    ]
