# Generated by Django 5.2 on 2025-05-03 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_disputechat_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputechat',
            name='moderator',
            field=models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_disputes', to=settings.AUTH_USER_MODEL),
        ),
    ]
