# Generated by Django 5.2 on 2025-05-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_disputechat_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusoption',
            name='deadline',
            field=models.IntegerField(verbose_name='Срок выполнения (дней)'),
        ),
        migrations.AlterField(
            model_name='bonusoption',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bonusoption',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bonusoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
