# Generated by Django 5.2 on 2025-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_bonusoption_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_order_change',
            field=models.BooleanField(default=False),
        ),
    ]
