# Generated by Django 5.2 on 2025-05-08 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_personalchat_personalmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalchat',
            name='order',
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personal_messages/'),
        ),
        migrations.AlterField(
            model_name='personalchat',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_chats_as_artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalchat',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_chats_as_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
