# Generated by Django 5.2 on 2025-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_personalchat_order_personalmessage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birzha',
            name='file',
        ),
        migrations.AddField(
            model_name='birzha',
            name='files',
            field=models.ManyToManyField(blank=True, to='main.file'),
        ),
    ]
